id: PA2358138
initial_creation_type: input
source_metadata:
  title: Sera Khandro Series
  language: pt
  description: 'Texts by and associated with Sera Khandro Kunzang Dekyong Wangmo (se
    ra mkha'' ''gro kun bzang bde skyong dbang mo, 1892–1940), the famous treasure-revealer:'
  volume:
    51e28bb8ab974717a5d126450482f9e9:
      title: Advice from the Vajra Wisdom Consort
      parent: Advice
    2b3453f02544497b9cdd2cf4b7e67944:
      title: Concise Spiritual Advice
      parent: Advice
    62611eafa7f146099fc5557905a8f1e7:
      title: 'The Excellent Path of Devotion: An Abridged Story of a Mendicant’s Experiences
        in Response to Questions from Vajra Kin'
      parent: Biography
    c9ba44add9a64961804482fcb79096da:
      title: Guru Yoga
      parent: Guru Yoga
    ce69011de1044513b887c736bcbd23da:
      title: 'The Profound Path of Guru Yoga: A Way to Freedom for the Fortunate'
      parent: Guru Yoga
    2212efa63c774cb98ec9960adbd3fc09:
      title: A Brief Prayer to Sera Khandro
      parent: Prayers
    d9b423f707ce4e4dbc332802691ec418:
      title: A Supplication to Noble Tārā, The Wish-Fulfilling Cornucopia
      parent: Prayers
    674babb9fcaf4686a1e5c4fe94286247:
      title: 'Burgeoning Benefit and Happiness: An Aspiration to be Reborn in the
        Land of Turquoise Leaves'
      parent: Prayers
    0c1134a67ecf4d15aff2e29c60abff77:
      title: 'Cloud Banks of Blessings: A Brief Prayer to the Garland of Successive
        Rebirths'
      parent: Prayers
    9f6c1508ec1d4c78adc0998e82b74552:
      title: 'The Hook of Compassion: A Prayer to the Garland of Successive Rebirths'
      parent: Prayers
    048131438cc34d0684f078b8436ec6a1:
      title: A Concise Meditation and Mantra Recitation of Sarasvatī from the Heart
        Essence of the Ḍākinī of Suchness (Chönyi Khandrö Tuktik)
      parent: Sādhanas
    df3466cda814465aa485c1875bea7fc3:
      title: 'The Profound Bestowal of Blessings: A Sādhana of Dorje Drolö from the
        Reality Ḍākinīs'' Secret Treasury (Chönyi Khandrö Sangdzö)'
      parent: Sādhanas
    fc64559c175d44e1bfc448c103fa00c9:
      title: A Song of Amazement Inspired by Practice Experience
      parent: Songs
created_at: '2022-03-01T01:29:57.559385'
last_modified_at: '2022-03-01T01:29:57.559388'
